#!/usr/bin/env bash
# ingest_evidence_bundle.sh
#
# Submit a QuantFidelity evidence bundle via the qf CLI.
#
# Not for production without proper secret management.
# Not investment advice.  Deterministic — no external APIs.
#
# Usage:
#   QUANTFIDELITY_STRATEGY_ID=<uuid> bash scripts/ingest_evidence_bundle.sh
#
# Environment variables:
#   QUANTFIDELITY_STRATEGY_ID   (required) UUID of the target strategy
#   QUANTFIDELITY_BASE_URL      (optional) Server URL (default: http://localhost:8000)
#   QUANTFIDELITY_API_KEY       (optional) API key — passed via env, never printed
#   QUANTFIDELITY_BUNDLE_FILE   (optional) Path to bundle JSON (default: sdk/python/examples/bundle.json)
#   QUANTFIDELITY_IDEMPOTENCY_KEY (optional) Idempotency key — auto-generated if not set

set -euo pipefail

# ---------------------------------------------------------------------------
# Resolve configuration from environment
# ---------------------------------------------------------------------------

QF_BASE_URL="${QUANTFIDELITY_BASE_URL:-http://localhost:8000}"
QF_STRATEGY_ID="${QUANTFIDELITY_STRATEGY_ID:-}"
QF_BUNDLE_FILE="${QUANTFIDELITY_BUNDLE_FILE:-sdk/python/examples/bundle.json}"
QF_IDEMPOTENCY_KEY="${QUANTFIDELITY_IDEMPOTENCY_KEY:-}"
# QUANTFIDELITY_API_KEY is read from the environment by the qf CLI automatically.
# We do NOT print or echo it here.

# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

if [[ -z "$QF_STRATEGY_ID" ]]; then
  echo "Error: QUANTFIDELITY_STRATEGY_ID is required." >&2
  echo "  Set it with: export QUANTFIDELITY_STRATEGY_ID=<uuid>" >&2
  exit 1
fi

if [[ ! -f "$QF_BUNDLE_FILE" ]]; then
  echo "Error: bundle file not found: $QF_BUNDLE_FILE" >&2
  echo "  Set QUANTFIDELITY_BUNDLE_FILE to override the path." >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Build the command
# ---------------------------------------------------------------------------

echo "QuantFidelity Evidence Ingestion"
echo "  Server:      $QF_BASE_URL"
echo "  Strategy ID: $QF_STRATEGY_ID"
echo "  Bundle file: $QF_BUNDLE_FILE"

QF_CMD=(
  qf ingest
  --base-url "$QF_BASE_URL"
  --strategy-id "$QF_STRATEGY_ID"
  --file "$QF_BUNDLE_FILE"
  --buffer-on-failure
)

# Append idempotency key if set
if [[ -n "$QF_IDEMPOTENCY_KEY" ]]; then
  echo "  Idempotency: $QF_IDEMPOTENCY_KEY"
  QF_CMD+=(--idempotency-key "$QF_IDEMPOTENCY_KEY")
else
  echo "  Idempotency: (auto-generated by SDK)"
fi

echo ""

# ---------------------------------------------------------------------------
# Execute
# ---------------------------------------------------------------------------

# QUANTFIDELITY_API_KEY is passed via the environment — it is never printed
# or echoed by this script.
exec "${QF_CMD[@]}"
